# Generated by Django 5.0.6 on 2026-05-20 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicepermission",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="devicepermission",
            name="granted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grants_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devicepermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="devicepermission",
            index=models.Index(
                fields=["device", "user"], name="accounts_de_device__3212f0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="devicepermission",
            constraint=models.UniqueConstraint(
                fields=("user", "device"), name="uq_user_device_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["organization", "role"], name="accounts_us_organiz_f36d76_idx"
            ),
        ),
    ]
