# Generated by Django 5.0.6 on 2026-05-20 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_groups",
                        to="accounts.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="devices.devicegroup",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "serial",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("robot", "Robot"),
                            ("drone", "Drone"),
                            ("sensor_hub", "Sensor Hub"),
                            ("gateway", "Gateway"),
                            ("camera", "Camera"),
                            ("actuator", "Actuator"),
                            ("wearable", "Healthcare Wearable"),
                            ("vehicle", "Autonomous Vehicle"),
                            ("controller", "Industrial Controller (PLC)"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("degraded", "Degraded"),
                            ("maintenance", "Maintenance"),
                            ("error", "Error"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=64)),
                ("model_number", models.CharField(blank=True, max_length=128)),
                ("manufacturer", models.CharField(blank=True, max_length=128)),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("battery_level", models.FloatField(blank=True, null=True)),
                ("signal_strength", models.IntegerField(blank=True, null=True)),
                ("health_score", models.FloatField(default=100.0)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("altitude", models.FloatField(blank=True, null=True)),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Declared abilities, e.g. {'commands': ['move','dock'], 'has_camera': true}",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("auth_token_hash", models.CharField(blank=True, max_length=128)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="accounts.organization",
                    ),
                ),
                (
                    "service_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="devices.devicegroup",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DeviceHealthSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("health_score", models.FloatField()),
                ("battery_level", models.FloatField(blank=True, null=True)),
                ("signal_strength", models.IntegerField(blank=True, null=True)),
                ("cpu_percent", models.FloatField(blank=True, null=True)),
                ("memory_percent", models.FloatField(blank=True, null=True)),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("uptime_seconds", models.BigIntegerField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_snapshots",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("command", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("acked", "Acknowledged"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="devices.device",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commands_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["device", "status"],
                        name="devices_dev_device__0a9c1c_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="devices_dev_status_59be3c_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="devicegroup",
            index=models.Index(
                fields=["organization", "parent"], name="devices_dev_organiz_36cd4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "status"], name="devices_dev_organiz_c0273e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["organization", "device_type"],
                name="devices_dev_organiz_6df431_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["status", "last_seen"], name="devices_dev_status_b6dd78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicehealthsnapshot",
            index=models.Index(
                fields=["device", "-created_at"], name="devices_dev_device__e7a080_idx"
            ),
        ),
    ]
