# Generated by Django 5.0.6 on 2026-05-20 22:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraFeed",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("rtsp", "RTSP"),
                            ("webrtc", "WebRTC"),
                            ("hls", "HLS"),
                            ("mjpeg", "MJPEG"),
                        ],
                        default="rtsp",
                        max_length=10,
                    ),
                ),
                ("stream_url", models.URLField(max_length=512)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_snapshot",
                    models.ImageField(blank=True, null=True, upload_to="snapshots/"),
                ),
                ("last_snapshot_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True, help_text="e.g. 1920x1080", max_length=20
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camera_feeds",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ("device", "name"),
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "key",
                    models.CharField(
                        help_text="Payload key, e.g. 'temp_c'", max_length=64
                    ),
                ),
                (
                    "sensor_type",
                    models.CharField(
                        choices=[
                            ("temperature", "Temperature"),
                            ("humidity", "Humidity"),
                            ("motion", "Motion"),
                            ("gps", "GPS"),
                            ("battery", "Battery"),
                            ("pressure", "Pressure"),
                            ("light", "Light"),
                            ("sound", "Sound / Noise"),
                            ("gas", "Gas / Air Quality"),
                            ("proximity", "Proximity / Distance"),
                            ("current", "Current / Power"),
                            ("vibration", "Vibration"),
                            ("heart_rate", "Heart Rate"),
                            ("camera", "Camera"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="°C, %, lux, ppm, …", max_length=24
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_value", models.FloatField(blank=True, null=True)),
                ("last_value_text", models.CharField(blank=True, max_length=255)),
                ("last_reading_at", models.DateTimeField(blank=True, null=True)),
                ("min_threshold", models.FloatField(blank=True, null=True)),
                ("max_threshold", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensors",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ("device", "name"),
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True)),
                ("value_text", models.CharField(blank=True, max_length=255)),
                ("value_json", models.JSONField(blank=True, null=True)),
                ("quality", models.SmallIntegerField(default=100)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="devices.device",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="telemetry.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ("-time",),
            },
        ),
        migrations.AddIndex(
            model_name="sensor",
            index=models.Index(
                fields=["device", "sensor_type"], name="telemetry_s_device__e008f7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sensor",
            constraint=models.UniqueConstraint(
                fields=("device", "key"), name="uq_sensor_device_key"
            ),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["sensor", "-time"], name="idx_reading_sensor_time"
            ),
        ),
        migrations.AddIndex(
            model_name="reading",
            index=models.Index(
                fields=["device", "-time"], name="idx_reading_device_time"
            ),
        ),
    ]
